[package]
name = "moteur_jeu_video"
version = "0.1.0"
authors = ["SailorSparkle <50321866+SailorSparkle@users.noreply.github.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# Bibliothèque SDL2, permettant d'utiliser OpenGL
# Article suivi : https://nercury.github.io/rust/opengl/tutorial/2018/02/08/opengl-in-rust-from-scratch-01-window.html
# MEGA IMPORTANT : Sur Linux, il faut installer la librairie :
# sudo apt install libsdl2-dev
# Sur Windows... https://nercury.github.io/rust/opengl/tutorial/2018/02/08/opengl-in-rust-from-scratch-01-window.html#initializing-sdl
sdl2 = "*"
