[package]
name = "moteurJeuVideo"
version = "0.1.0"
authors = ["SailorSparkle <50321866+SailorSparkle@users.noreply.github.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
