[package]
name = "base"
version = "0.1.0"
authors = ["technolapin <clement.chomicki@protonmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
glutin="0.21.2"

# pour les tests
rand="*"